### ISSUE TITLE
Describe migration from CUBA

### ISSUE THREAD

**Issue by Rumata42** [jmix-framework/jmix-v1-v2-docs#238] opened 2021-08-18 10:23 UTC
The auto-migration of projects from CUBA to Jmix platforms was implemented here https://youtrack.haulmont.com/issue/JST-49.
In that ticket, there is an inner instruction to using the migration and a link to a manual migration guide.

**Comment by knstvk** [comment] 2021-08-25 07:01
Duplicate of #187

**Closed as completed by knstvk** 2021-08-25 07:01 UTC
Labels: in: studio
