### ISSUE TITLE
Change a link for JDK download

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix-v1-v2-docs#233] opened 2021-08-03 06:12 UTC
The following section https://docs.jmix.io/jmix/1.0/setup.html#jdk suggests to download JDK from https://adoptopenjdk.net,but AdoptOpenJDK has recently been rebranded and moved to the Eclipse Foundation. Now it can be downloaded from the https://adoptium.net/

**Comment by knstvk** [comment] 2021-08-25 06:57
Duplicate of #236

**Closed as completed by knstvk** 2021-08-25 06:57 UTC
Labels: state: duplicate
