### ISSUE TITLE
Keep the current topic when switching between Jmix versions 1 and 2

### ISSUE THREAD

**Issue by vfadeevGit** [jmix-framework/jmix-v1-v2-docs#753] opened 2024-05-22 07:20 UTC
Use case description:
1. Open the documentation. It automatically opens Jmix 2 version
2. Find some specific article like https://docs.jmix.io/1.x/jmix/1.5/data-access/fetching.html
3. Switch to Jmix 1 version in the header navigation bar and the current topic will be dropped to the Intro

This use case is important for those, who are still working with Jmix 1.X and forget to switch the Jmix version after opening the documentation page. It is also useful when developers see that some information in Jmix 2.X is missing and they would like to check the same in Jmix 1.X version

**Comment by knstvk** [comment] 2024-11-14 12:11
The problem is mainly resolved in #897 and #915

**Closed as not planned by knstvk** 2024-11-14 12:11 UTC
